version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      tokio:
        patterns:
          - "tokio*"
      tracing:
        patterns:
          - "tracing*"
      serde:
        patterns:
          - "serde*"
          - "postcard"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "actions/*"
          - "dtolnay/*"
          - "Swatinem/*"
          - "taiki-e/*"
