/**
 * Type declarations for the `@tese/cyclonedds-wasm` package (Phase H).
 *
 * These describe the wasm-bindgen export surface in
 * `cyclonedds-wasm/src/js.rs`, as generated by
 * `wasm-pack build --target web|nodejs`. The `.wasm` + generated glue
 * live in `./pkg/` (web) or `./pkg-node/` (node) after `npm run build`;
 * this file is handwritten and checked in so TS consumers get types
 * without running the build.
 *
 * 64-bit rule: every `u64`/`i64` crosses the boundary as `bigint`,
 * never as `number` (exact above `Number.MAX_SAFE_INTEGER`).
 */

/** One decoded echo sample on the binary data plane. */
export interface EchoSample {
  topic: string;
  id: number;
  text: string;
  values: Int32Array;
  seq: number;
}

/** Connected bridge client. Obtain via {@link WasmClient.connect}. */
export class WasmClient {
  private constructor();

  /**
   * Async initialization: resolves with the client after the WebSocket
   * `open` handshake, rejects with a typed string (`"timeout: ..."`,
   * `"connection closed before open"`, or `"WebSocket error: ..."`) on
   * failure. `timeoutMs === 0` disables the client-side timeout (race
   * your own deadline in that case).
   */
  static connect(url: string, timeoutMs: number): Promise<WasmClient>;

  /** Publish one echo sample as a binary CDR frame (`ArrayBuffer`). */
  send_echo(topic: string, id: number, text: string, values: number[] | Int32Array): void;

  /**
   * Register the echo callback. Replaces any previous callback.
   * Samples for other topics, non-CDR frames, and malformed CDR are
   * dropped (never throw into the socket handler).
   */
  on_echo(callback: (sample: EchoSample) => void): void;

  /** Idempotent disconnect; calling twice never throws. */
  close(): void;

  free(): void;
}

/** Wrap a Rust `u64` as an exact JS `bigint`. */
export function u64_to_bigint(v: bigint): bigint;

/** `bigint` -> Rust `u64`; throws on negative or > 2^64-1. */
export function bigint_to_u64(v: bigint): bigint;

/** Wrap a Rust `i64` as an exact JS `bigint`. */
export function i64_to_bigint(v: bigint): bigint;

/** `bigint` -> Rust `i64`; throws outside [-2^63, 2^63-1]. */
export function bigint_to_i64(v: bigint): bigint;

/** Default export: async wasm initialization (wasm-pack glue). */
export default function init(input?: string | URL | ArrayBuffer | Response): Promise<void>;
