// ABI snapshot for x86_64-pc-windows-msvc.
//
// Generated by the native ABI probe in build.rs and committed so that a
// *cross*-compile to this target has measured constants instead of guessed
// ones: the probe is a C program that has to run on the target to answer, so
// when host != target build.rs refuses to continue without one of these.
//
// Regenerate with `scripts/capture-abi-snapshot.sh` after a native build on
// this target. Do not edit by hand — every constant here is a measurement.
//
// Source: CycloneDDS 11.0.0 (cyclonedds-src), rustc 1.85.0.
pub const PROBE_DDS_SAMPLE_INFO_SIZE: usize = 64;
pub const PROBE_OFF_SAMPLE_STATE: usize = 0;
pub const PROBE_OFF_VIEW_STATE: usize = 4;
pub const PROBE_OFF_INSTANCE_STATE: usize = 8;
pub const PROBE_OFF_VALID_DATA: usize = 12;
pub const PROBE_OFF_SOURCE_TIMESTAMP: usize = 16;
pub const PROBE_OFF_INSTANCE_HANDLE: usize = 24;
pub const PROBE_DDS_TIME_T_SIZE: usize = 8;
pub const PROBE_DDS_DURATION_T_SIZE: usize = 8;
pub const PROBE_DDS_ENTITY_T_SIZE: usize = 4;
pub const PROBE_DDS_RETURN_T_SIZE: usize = 4;
pub const PROBE_DDS_INSTANCE_HANDLE_T_SIZE: usize = 8;
pub const PROBE_DDS_ATTACH_T_SIZE: usize = 8;
pub const PROBE_DDS_GUID_T_SIZE: usize = 16;
pub const PROBE_SERDATA_OFF_OPS: usize = 0;
pub const PROBE_SERDATA_OFF_HASH: usize = 8;
pub const PROBE_SERDATA_OFF_REFC: usize = 12;
pub const PROBE_SERDATA_OPS_OFF_GET_SIZE: usize = 8;
pub const PROBE_SERDATA_OPS_OFF_TO_SER: usize = 48;
pub const PROBE_SERDATA_OPS_OFF_FREE: usize = 96;
pub const PROBE_INCONSISTENT_TOPIC_SIZE: usize = 8;
pub const PROBE_LIVELINESS_LOST_SIZE: usize = 8;
pub const PROBE_LIVELINESS_CHANGED_SIZE: usize = 24;
pub const PROBE_OFFERED_DEADLINE_MISSED_SIZE: usize = 16;
pub const PROBE_OFFERED_INCOMPATIBLE_QOS_SIZE: usize = 12;
pub const PROBE_REQUESTED_DEADLINE_MISSED_SIZE: usize = 16;
pub const PROBE_REQUESTED_INCOMPATIBLE_QOS_SIZE: usize = 12;
pub const PROBE_SAMPLE_LOST_SIZE: usize = 8;
pub const PROBE_SAMPLE_REJECTED_SIZE: usize = 24;
pub const PROBE_PUBLICATION_MATCHED_SIZE: usize = 24;
pub const PROBE_SUBSCRIPTION_MATCHED_SIZE: usize = 24;
