[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,/Users/zeitune/Documents/tese/cyclonedds/build-mac/lib"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,/Users/zeitune/Documents/tese/cyclonedds/build-mac/lib"]
