#!/usr/bin/env bash
#
# Capture the ABI probe's output for the host target into
# cyclonedds-rust-sys/abi/<triple>.rs.
#
# Why this exists: the probe in cyclonedds-rust-sys/build.rs is a C program that
# measures struct sizes and field offsets by running. That answer is only
# available on the machine it runs on, so a *cross*-compile has nothing to go on
# and build.rs refuses to continue (FFI-ABI-008) unless a snapshot taken from a
# native build on that target is committed.
#
# Run this on each target you intend to cross-compile *to*, natively, and commit
# the result. There is no way to produce a linux snapshot from Windows, or an
# aarch64 one from x86_64 — that is the whole point of the check.
#
# Usage:
#   scripts/capture-abi-snapshot.sh
#
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
triple="$(rustc -vV | awk '/^host:/ {print $2}')"
abi_dir="$repo_root/cyclonedds-rust-sys/abi"
dest="$abi_dir/$triple.rs"

echo "==> building cyclonedds-rust-sys natively for $triple"
cargo build --manifest-path "$repo_root/cyclonedds-rust-sys/Cargo.toml" >/dev/null

target_dir="${CARGO_TARGET_DIR:-$repo_root/target}"
probe="$(find "$target_dir" -name abi_probe.rs -path '*cyclonedds-rust-sys*' \
    -newer "$repo_root/cyclonedds-rust-sys/build.rs" 2>/dev/null | head -1)"
if [ -z "$probe" ]; then
    probe="$(find "$target_dir" -name abi_probe.rs -path '*cyclonedds-rust-sys*' | head -1)"
fi
if [ -z "$probe" ]; then
    echo "abi_probe.rs not found under $target_dir — did the build run the probe?" >&2
    exit 1
fi

cyclonedds_version="$(
    grep -m1 'project(CycloneDDS' "$repo_root/cyclonedds-src/src/cyclonedds/CMakeLists.txt" \
        | sed -E 's/.*VERSION ([0-9.]+).*/\1/'
)"
rustc_version="$(rustc --version | awk '{print $2}')"

mkdir -p "$abi_dir"
{
    echo "// ABI snapshot for $triple."
    echo "//"
    echo "// Generated by the native ABI probe in build.rs and committed so that a"
    echo "// *cross*-compile to this target has measured constants instead of guessed"
    echo "// ones: the probe is a C program that has to run on the target to answer, so"
    echo "// when host != target build.rs refuses to continue without one of these."
    echo "//"
    echo "// Regenerate with \`scripts/capture-abi-snapshot.sh\` after a native build on"
    echo "// this target. Do not edit by hand — every constant here is a measurement."
    echo "//"
    echo "// Source: CycloneDDS $cyclonedds_version (cyclonedds-src), rustc $rustc_version."
    cat "$probe"
} > "$dest"

echo "==> wrote $dest"
echo
echo "Commit it. If it differs from the previous snapshot, that difference is an"
echo "ABI change: understand it before accepting it."
